### ISSUE TITLE
suggestion: fish oil should be drinkable

### ISSUE THREAD

**Issue by jshipley** [PixelPacker/FishingAquatica#6]
You should be able to drink the fish oil to fill some hunger / satiation, maybe somewhere in between the amount you get from a raw and cooked fish.

Optionally, since fish oil is often treated as a folk remedy, I think it would be great if drinking fish oil had the same negative status removal effect that milk does. You could also make it so that fish oil is a food you can keep consuming even if you're full.

**Comment by Byte-Oracle** [comment]
I actually really like the idea of adding functionally to fish oil!
However, I think I mainly like the idea of giving the effect removing function, but that feels a bit too powerful with how easy it is to obtain a large quantity of it.

How would having it so it would remove the potion effect and also apply nausea to the player (Due to the nasty taste and oily texture) feel to you?

**Comment by jshipley** [comment]
I like that idea a lot. It makes it fun and interesting.

I think that nausea (wobbly screen) might be a bit extreme, but maybe you could make it work like rotten flesh: consuming it gives an 80% chance of inflicting the hunger effect. It would be even better if hunger was the only status effect that drinking fish oil could not remove (I can't imagine that drinking fish oil would help you to recover from the sick feeling from drinking fish oil).

Even after you have penned in a couple of cows and have unlimited access to milk, I think that the fish oil might be a decent choice for emergency effect cleanser since fish oil stacks and milk doesn't.

**Comment by Byte-Oracle** [comment]
Closed with https://github.com/PixelPacker/FishingAquatica/commit/668c2eae2dbdb58825f4a7b8d5bd203c9b81189e
